### PR TITLE
Adhere to websocket paths in IPython 3.x

### PR DESCRIPTION
**Pull request by rgbkrk**

### CODE REVIEW

**Comment by minrk** [comment]
Just to be clear - JupyterHub requires IPython 3. This is appropriate for tmpnb, though, depending on how much you want to share.

**Comment by rgbkrk** [comment]
I can tear out the "legacy" paths then.

**Comment by rgbkrk** [comment]
Updated.

**Comment by rgbkrk** [comment]
The only reason I kept it in was that since the pathing is the same between JupyterHub and tmpnb and they're running roughly the same containers, it made sense to maintain one set of nginx configuration.

**Pull request merged**
