### PR TITLE
Launch docker containers with swarm

### PR DESCRIPTION
**Pull request by jhamrick**
This works currently, but isn't quite compatible with jupyterhub because 1) swarm prefixes the container names with the node name, which means dockerspawner can't look up the containers, and 2) jupyterhub expects the single user server to be running on the same machine.

### CODE REVIEW

**Comment by rgbkrk** [comment]
> 1) swarm prefixes the container names with the node name, which means dockerspawner can't look up the containers

Hmmm... That's going to affect how we do things too @smashwilson.

> 2) jupyterhub expects the single user server to be running on the same machine.

Will we be able to get past this abstraction? Here I thought it was just about being on the same path.

**Comment by minrk** [comment]
> > 2) jupyterhub expects the single user server to be running on the same machine.
> 
> Will we be able to get past this abstraction? Here I thought it was just about being on the same path.

We talked about this one on gitter. It should be fine as long as the single-user servers are visible from the Hub and proxy (Hub for checking that it's up, proxy for forwarding requests). There are not yet any examples of setting the ip of single-user servers at the moment, but setting `user.server.ip` should be fully supported in the same way that `user.server.port` is set in `Spawner.start`.

**Comment by jhamrick** [comment]
> Will we be able to get past this abstraction? Here I thought it was just about being on the same path.

Regarding this, I am working on a subclass of `SystemUserSpawner` that parses out the container name, and also sets the IP (in the way that Min described).

**Comment by jhamrick** [comment]
It works! (Mostly)

Last thing to do is to create the users on the right server, because when they are added by the authenticator, that is to the system that JupyterHub is running on -- but really what we want is the system that the user's server is running on.

One thing I was thinking, though, is if the NFS mount is correctly chowned to the user's id on the JupyterHub server, then perhaps we don't actually need to create the users on the node server (because technically, the user doesn't actually have to exist, it's just the files that need to have the right UID). So then probably the best thing to do would be:
1. Have the NFS server run on the same server as JupyterHub, so the files are associated with the correct UIDs
2. Don't worry about creating users on the node servers
3. Create users just on the main server and in the single user containers (already happens)

Does this seem reasonable @rgbkrk @minrk ?

**Comment by rgbkrk** [comment]
Since I've never administered an NFS setup, I'm really not sure. At first glance...

```
root@compmodels-nfs-cli:/students# touch something
root@compmodels-nfs-cli:/students# ls -la
total 24
drwxrwxrwx  3 root   root     4096 Jan 15 15:54 .
drwxr-xr-x 23 root   root     4096 Jan  8 06:21 ..
drwx------  2 root   root    16384 Jan  8 05:10 lost+found
-rw-r--r--  1 nobody nogroup     0 Jan 15 15:54 something
```

I'm not sure how UIDs work over NFS.

**Comment by jhamrick** [comment]
Hmm, after chowning it, the UIDs do show up on the client server. On the host:

```
root@compmodels-gluster:/students# touch foo
root@compmodels-gluster:/students# ls -l foo
-rw-r--r-- 1 root   root        0 Jan 15 16:37 foo
root@compmodels-gluster:/students# chown 1007:1007 foo
root@compmodels-gluster:/students# ls -l foo
-rw-r--r-- 1   1007    1007     0 Jan 15 16:37 foo
```

and then on the client:

```
root@compmodels-nfs-cli:/students# ls -l foo
-rw-r--r-- 1 1007 1007 0 Jan 15 16:37 foo
```

and doing it the other way around works, too.

**Pull request merged**
